version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: binna
      POSTGRES_PASSWORD: binna123
      POSTGRES_DB: BinnaLibrary
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  binnalib-app:
    build: .
    container_name: binnalib-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/BinnaLibrary
      SPRING_DATASOURCE_USERNAME: binna
      SPRING_DATASOURCE_PASSWORD: binna123

volumes:
  postgres-data:
